import { ContainerModule } from 'inversify';
import { TRIGGER_HANDLER_REGISTRATION_SERVICE } from 'shared';
import { HTTP_CONTROLLER_TYPE, HttpControllerMetadataReader } from './decorators';
import { HttpControllerRegistrationService } from './http-controller-registration.service';
import { HttpHandlerSupportFactory } from './http-handler-support.factory';
import { HttpHandlerFactory } from './http-handler.factory';
import { HttpOperationsRegistrationService } from './http-operations-registration.service';
import { HttpRequestArgProviderFactory } from './http-request-arg-provider.factory';
import { HttpResponseProcessorFactory } from './http-response-processor.factory';
import { OpenApiDefinitionService } from './open-api-definition.service';
import { OpenApiMetadataService } from './open-api-metadata.service';
import { OpenApiPrintService } from './open-api-print.service';
import { OpenApiRegistrationService } from './open-api-registration.service';
import { AuthenticatorProvider } from './security/authenticator.provider';
import { OperationAuthenticationResolver } from './security/operation-authentication.resolver';
import { FallbackPrincipalMergeService } from './security/principal-merge.service';
import { StrictPrincipalMergeService } from './security/strict-principal-merge.servce';
import { SwaggerHandlingService } from './swagger-handling.service';

export * from './decorators';
export * from './http-controller-registration.service';
export * from './http-controller.model';
export * from './http-handler-support.factory';
export * from './open-api-definition.service';
export * from './open-api-print.service';
export * from './open-api-registration.service';
export * from './security';
export * from './swagger-handling.service';

export const HttpControllerModule = new ContainerModule(({ bind }) => {
  bind(HttpControllerMetadataReader).toSelf();
  bind(HttpHandlerFactory).toSelf();
  bind(TRIGGER_HANDLER_REGISTRATION_SERVICE).to(HttpControllerRegistrationService).whenNamed(HTTP_CONTROLLER_TYPE);
  bind(SwaggerHandlingService).toSelf();
  bind(HttpHandlerSupportFactory).toSelf();
  bind(HttpRequestArgProviderFactory).toSelf();
  bind(HttpResponseProcessorFactory).toSelf();
  bind(OpenApiMetadataService).toSelf();
  bind(AuthenticatorProvider).toSelf();
  bind(OperationAuthenticationResolver).toSelf();
  bind(OpenApiRegistrationService).toSelf();
  bind(OpenApiDefinitionService).toSelf();
  bind(HttpOperationsRegistrationService).toSelf();
  bind(OpenApiPrintService).toSelf();
  bind(FallbackPrincipalMergeService).toSelf();
  bind(StrictPrincipalMergeService).toSelf();
});
