export const INITIAL_DRIVERS = [
  { name: 'Markus', surname: 'Feldmann' },
  { name: 'Jana', surname: 'Reuter' },
  { name: 'Tobias', surname: 'Gruber' },
  { name: 'Anke', surname: 'Vollmer' },
  { name: 'Leonhard', surname: 'Stein' },
  { name: 'Miriam', surname: 'Kessler' },
  { name: 'Sven', surname: 'Albrecht' },
  { name: 'Katja', surname: 'Dorn' },
  { name: 'Holger', surname: 'Mertens' },
  { name: 'Silke', surname: 'Baumgart' },

  { name: 'Piotr', surname: 'Kowalski' },
  { name: 'Marek', surname: 'Nowicki' },
  { name: 'Zofia', surname: 'Brzezinska' },
  { name: 'Andrei', surname: 'Petrescu' },
  { name: 'Elena', surname: 'Ionescu' },
  { name: 'Viktor', surname: 'Havel' },
  { name: 'Daria', surname: 'Kovalenko' },
  { name: 'Tomasz', surname: 'Wrona' },
  { name: 'Bogdan', surname: 'Rusu' },
  { name: 'Natalia', surname: 'Sokolova' },

  { name: 'Carlos', surname: 'Mendes' },
  { name: 'Aisha', surname: 'Rahman' },
  { name: 'Daniel', surname: "O'Connor" },
  { name: 'Sofia', surname: 'Marin' },
  { name: 'Lucas', surname: 'Andrade' },
  { name: 'Priya', surname: 'Natarajan' },
  { name: 'Matteo', surname: 'Ricci' },
  { name: 'Chloe', surname: 'Bennett' },
  { name: 'Amir', surname: 'Haddad' },
  { name: 'Isabella', surname: 'Duarte' },

  { name: 'Ralf', surname: 'Neubauer' },
  { name: 'Heiko', surname: 'Schramm' },
  { name: 'Birgit', surname: 'Kronauer' },
  { name: 'Dennis', surname: 'Wittkamp' },
  { name: 'Florian', surname: 'Behrens' },
  { name: 'Uwe', surname: 'Kaltenbach' },
  { name: 'Nadine', surname: 'Schuster' },
  { name: 'Patrick', surname: 'Hollmann' },
  { name: 'Stefan', surname: 'Kreutz' },
  { name: 'Melanie', surname: 'Bergmann' },

  { name: 'Igor', surname: 'Mihailov' },
  { name: 'Svetlana', surname: 'Orlova' },
  { name: 'Roman', surname: 'Kravets' },
  { name: 'Lukasz', surname: 'Stachowiak' },
  { name: 'Emilia', surname: 'Nowak' },
  { name: 'Oleg', surname: 'Bondarenko' },
  { name: 'Kristina', surname: 'Markovic' },
  { name: 'Milan', surname: 'Petrovic' },
  { name: 'Jelena', surname: 'Stojanovic' },
  { name: 'Nikola', surname: 'Vukovic' },

  { name: 'Jonas', surname: 'Hinterseer' },
  { name: 'Sarah', surname: 'Linden' },
  { name: 'Kilian', surname: 'Forster' },
  { name: 'Lara', surname: 'Schaffner' },
  { name: 'Dominik', surname: 'Rehfeld' },
];
