/**
 * Console API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The destination point of the truck as a GeoJSON Point if it is on a run
 */
export interface TruckDestinationPoint {
  type: TruckDestinationPoint.TypeEnum;
  coordinates: Array<number>;
}
export namespace TruckDestinationPoint {
  export const TypeEnum = {
    Point: 'Point',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
