/**
 * Console API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The driver assigned to the truck
 */
export interface TruckDriver {
  /**
   * The unique identifier of the driver assigned to the truck
   */
  id: number;
  /**
   * The full name of the driver assigned to the truck
   */
  name: string;
}
