/**
 * Console API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The current location of the truck as a GeoJSON Point
 */
export interface TruckLocation {
  type: TruckLocation.TypeEnum;
  coordinates: Array<number>;
}
export namespace TruckLocation {
  export const TypeEnum = {
    Point: 'Point',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
