/**
 * Console API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Truck } from './truck';

export interface TrucksResponseDto {
  /**
   * The list of items for the current page
   */
  items: Array<Truck>;
  /**
   * The total number of items available
   */
  totalCount: number;
}
