/**
 * Console API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TruckDestinationPoint } from './truckDestinationPoint';
import { TruckDriver } from './truckDriver';
import { TruckLocation } from './truckLocation';

export interface Truck {
  /**
   * The unique identifier of the truck
   */
  id: number;
  /**
   * The license plate of the truck
   */
  licensePlate: string;
  /**
   * The model of the truck
   */
  model: string;
  driver?: TruckDriver;
  location: TruckLocation;
  /**
   * The current speed of the truck in km/h
   */
  speed: number;
  /**
   * The current acceleration of the truck in m/s²
   */
  acceleration: number;
  /**
   * The current fuel level of the truck as a percentage
   */
  fuelLevel: number;
  /**
   * The destination address of the truck if it is on a run
   */
  destinationAddress?: string;
  destinationPoint?: TruckDestinationPoint;
  /**
   * The current status of the truck
   */
  status: Truck.StatusEnum;
  run?: number;
}
export namespace Truck {
  export const StatusEnum = {
    idle: 'idle',
    en_route: 'en_route',
    loading: 'loading',
    unloading: 'unloading',
    maintenance: 'maintenance',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
